"""
Document generation tool — REAL, not a stub.

Builds an actual .docx approval note with python-docx, following the
required sections from the plant's approval-note workflow reference.

Owner: Track B.
"""
import os
from datetime import datetime

from docx import Document
from docx.shared import Pt, RGBColor

from .. import config

# Severity keywords, highest first — used for the severity summary line
_SEVERITY_RULES = [
    ("Critical", ["leak detected", "critical", "immediate"]),
    ("Major", ["corrosion", "crack", "exceed", "deviation"]),
    ("Minor", ["wear", "replace", "schedule", "recalibrate"]),
]


def _infer_severity(findings: list[str]) -> str:
    """Best-effort severity summary from the finding text. Deliberately
    conservative: anything unmatched is reported as Observation."""
    joined = " ".join(findings).lower()
    for level, keywords in _SEVERITY_RULES:
        if any(k in joined for k in keywords):
            return level
    return "Observation"


def draft_approval_note(source_name: str, findings: list[str], task_id: str) -> str:
    doc = Document()

    title = doc.add_heading("Approval Note", level=1)
    title.runs[0].font.color.rgb = RGBColor(0x1C, 0x5D, 0x99)

    meta = doc.add_paragraph()
    meta.add_run("Generated by: UrjaKavach Sovereign AI Workbench\n").bold = True
    meta.add_run(f"Source document: {source_name}\n")
    meta.add_run(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n")
    meta.add_run(f"Task ID: {task_id}")

    doc.add_heading("Key Findings", level=2)
    if findings:
        for f in findings:
            doc.add_paragraph(f, style="List Bullet")
    else:
        doc.add_paragraph("No significant findings extracted.")

    doc.add_heading("Severity Summary", level=2)
    doc.add_paragraph(f"Highest severity present: {_infer_severity(findings)}")

    doc.add_heading("Recommendation", level=2)
    doc.add_paragraph(
        "Findings above are flagged for review by the responsible engineer. "
        "This note was drafted automatically from the scanned source document "
        "and must be verified before formal sign-off."
    )

    doc.add_heading("Sign-off", level=2)
    doc.add_paragraph("Responsible Engineer: ______________________    Date: ____________")

    footer = doc.add_paragraph()
    run = footer.add_run(
        "Generated entirely on-premise. No data left the facility."
    )
    run.italic = True
    run.font.size = Pt(9)

    out_path = os.path.join(config.OUTPUTS_DIR, f"approval_note_{task_id}.docx")
    doc.save(out_path)
    return out_path
